tasks:
  -
    name: banana_base_task  # task name
    asset_root: workflows/simbox/assets
    task: BananaBaseTask  # !! where you specify TASK class
    task_id: 0

    offset: null
    render: True


    # Arena configuration
    arena_file: workflows/simbox/core/configs/arenas/pick_randomized_arena.yaml
    # arena_file: workflows/simbox/core/configs/arenas/scene_arena.yaml

    env_map:
      envmap_lib: envmap_lib
      apply_randomization: True
      intensity_range: [4000, 7000]
      rotation_range: [0, 180]

    robots:
      -
        name: "lift2"
        robot_config_file: workflows/simbox/core/configs/robots/lift2.yaml
        euler: [0.0, 0.0, 90.0]
        left_joint_home: [-0.00059017,  0.00374724,  0.00516233,  0.00025332, -0.00105036, -0.00132419]
        right_joint_home: [-0.00059017,  0.00374724,  0.00516233,  0.00025332, -0.00105036, -0.00132419]
        left_joint_home_std: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
        right_joint_home_std: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
        ignore_substring: ["material"]

    objects:
      -
        name: close_v_right
        target_class: ArticulatedObject
        dataset: pm
        info_name: "close_v"
        euler: [0.0, 0.0, 0.0]
        scale: [0.001, 0.001, 0.001]
        joint_position_range: [0.6, 0.8]
        apply_randomization: True
        path: ""
        category: ""
        obj_info_path: ""
        art_cat: art/microwave_gr

    regions:
      -
        object: close_v_right
        target: table
        random_type: A_on_B_region_sampler
        random_config:
          pos_range: [
            [-0.05, 0.0, 0.0],
            [0.25, 0.15, 0.0]
          ]
          yaw_rotation: [-30, 30]
      -
        object: lift2
        target: table
        random_type: A_on_B_region_sampler
        random_config:
          pos_range: [
            [-0.025, -0.8, -0.7],
            [0.025, -0.80, -0.6]
          ]
          yaw_rotation: [0.0, 0.0]

    cameras:
      -
        name: lift2_hand_left
        translation: [0.07, 0.01, 0.08]
        orientation: [0.62, 0.33, -0.33, -0.62]
        camera_axes: usd
        camera_file: workflows/simbox/core/configs/cameras/realsense_d405.yaml
        parent: "lift2/lift2/lift2/fl/link6"  # todo
        apply_randomization: True
        max_translation_noise: 0.02
        max_orientation_noise: 2.5
      -
        name: lift2_hand_right
        translation: [0.07, 0.01, 0.08]
        orientation: [0.62, 0.33, -0.33, -0.62]
        camera_axes: usd
        camera_file: workflows/simbox/core/configs/cameras/realsense_d405.yaml
        parent: "lift2/lift2/lift2/fr/link6"
        apply_randomization: True
        max_translation_noise: 0.02
        max_orientation_noise: 2.5
      -
        name: lift2_head
        translation: [0.1, 0.02, 0.03]
        orientation: [0.6602, 0.2534, -0.2534, -0.6602]
        camera_axes: usd
        camera_file: workflows/simbox/core/configs/cameras/realsense_d455_v3.yaml
        parent: "lift2/lift2/lift2/h_link6"  # todo: robot base frame
        apply_randomization: True
        max_translation_noise: 0.03
        max_orientation_noise: 5.0

    data:
      task_dir: "close_the_microwave_part2"
      language_instruction: "Close the microwave with right arm."
      detailed_language_instruction: "Close the microwave door with the right robotic arm."
      collect_info: ""
      version: "v3.0, head camerea 1280x720, wrist 640x480, y 45 degrees"
      update: True
      max_episode_length: 600

    skills:
      -
        lift2:
          -
            right:
              -
                name: close
                objects: [close_v_right]
                # debug start: KPAMPlanner
                planner_setting:
                  task_name: CloseBox
                  category_name: Articulated

                  tool_keypoint_name_list: [tool_head, tool_tail, tool_side]
                  object_keypoint_name_list: [articulated_object_head, articulated_object_tail]
                  success_threshold: 0.08
                  constraint_list:
                    # ensure the gripper to be in contact with the box lid with whole fingers
                    - keypoint_name: tool_head
                      target_keypoint_name: articulated_object_head
                      tolerance: 0.0001
                      type: point2point_constraint
                      name: fingers_contact_with_link0

                    # ensure surface of the gripper to be parallel to the box lid
                    - axis_from_keypoint_name: tool_head
                      axis_to_keypoint_name: tool_side
                      cross_target_axis1_from_keypoint_name: articulated_object_head
                      cross_target_axis1_to_keypoint_name: articulated_object_tail
                      target_axis: link0_contact_axis
                      target_axis_frame: object
                      tolerance: 0.005
                      target_inner_product: -1
                      type: frame_axis_parallel
                      name: hand_parallel_to_link0_edge_door

                    - axis_from_keypoint_name: tool_head
                      axis_to_keypoint_name: tool_tail
                      cross_target_axis1_from_keypoint_name: articulated_object_head
                      cross_target_axis1_to_keypoint_name: articulated_object_tail
                      target_axis: link0_contact_axis
                      target_axis_frame: object    # cross_target_axis2_frame
                      tolerance: 0.005
                      target_inner_product: 0.7
                      type: frame_axis_parallel  # enforce parallelism via cross product constraint
                      name: fingers_orthogonal_to_link0

                  contact_pose_index: 2
                  # pre-actuation pose list.
                  pre_actuation_motions: [ ["translate_x", -0.05]]  #   ["translate_z", -0.0001] , ["translate_x", -0.01],
                  # post-actuation pose list
                  post_actuation_motions:  [ ["rotate",0.15],["rotate",0.15], ["rotate",0.15],  ["rotate",0.1], ["rotate",0.1],["rotate",0.1], ["rotate",0.1], ["rotate",0.1], ["rotate",0.1],["rotate",0.1],["rotate",0.05], ["rotate",0.05]] # ["translate_z", 0.08],
                  # post_actuation_motions:  [ ["rotate",0.1],["rotate",0.1], ["rotate",0.1],  ["rotate",0.1], ["rotate",0.1],["rotate",0.05], ["rotate",0.05], ["rotate",0.05], ["rotate",0.05], ["rotate",0.05]] # ["translate_z", 0.08],

                  # in link8 frame, in degree, in metre
                  keypose_random_range:
                    orientation:  # rotation around each axis (degrees)
                      x_min: -25
                      x_max: 25
                      y_min: -3
                      y_max: 3
                      z_min: -3
                      z_max: 3
                    position:
                      x_min: -0.02 # -0.1
                      x_max: 0.0 # 0.0
                      y_min: 0.0 # -0.02
                      y_max: 0.1 # 0.0
                      z_min: -0.05 # -0.05
                      z_max: 0.0 # 0.0
