tasks:
  -
    name: banana_base_task  # task name
    asset_root: workflows/simbox/assets
    task: BananaBaseTask  # !! where you specify TASK class
    task_id: 0

    offset: null
    render: True


    # Arena configuration
    arena_file: workflows/simbox/core/configs/arenas/table_clean_arena.yaml

    env_map:
      envmap_lib: envmap_lib
      apply_randomization: True
      intensity_range: [5000, 5500]
      rotation_range: [0, 180]

    robots:
      -
        name: "split_aloha"
        robot_config_file: workflows/simbox/core/configs/robots/split_aloha.yaml
        euler: [0.0, 0.0, 90.0]
        # left_joint_home: [0.00484993, 0.34198609, -0.14007858, 0.01680429, 0.14391101, -0.00252178]
        # right_joint_home: [0.00484993, 0.34198609, -0.14007858, 0.01680429, 0.14391101, -0.00252178]
        # left_joint_home_std: [0.12513939, 0.24539099, 0.24468172, 0.23398885, 0.2710117, 0.21726329]
        # right_joint_home_std: [0.12513939, 0.24539099, 0.24468172, 0.23398885, 0.2710117, 0.21726329]
        constrain_grasp_approach: True

        ignore_substring: ["material", "table"]

    objects:
      -
        name: place_object
        path: "basic/stack_bowls/omniobject3d-bowl/omniobject3d-bowl_002/Aligned_obj.usd"
        target_class: RigidObject
        dataset: oo3d
        category: "bowl"
        prim_path_child: Aligned
        translation: [0.0, 0.0, 0.0]
        euler: [90.0, 0.0, 0.0]
        scale: [0.001, 0.001, 0.001]
        orientation_mode: keep
      -
        name: pick_object_left2
        path: "basic/stack_bowls/omniobject3d-bowl/omniobject3d-bowl_002/Aligned_obj.usd"
        target_class: RigidObject
        dataset: oo3d
        category: "bowl"
        prim_path_child: Aligned
        translation: [0.0, 0.0, 0.0]
        euler: [90.0, 0.0, 0.0]
        scale: [0.001, 0.001, 0.001]
        orientation_mode: keep
      -
        name: pick_object_right1
        path: "basic/stack_bowls/omniobject3d-bowl/omniobject3d-bowl_002/Aligned_obj.usd"
        target_class: RigidObject
        dataset: oo3d
        category: "bowl"
        prim_path_child: Aligned
        translation: [0.0, 0.0, 0.0]
        euler: [90.0, 0.0, 0.0]
        scale: [0.001, 0.001, 0.001]
        orientation_mode: keep

    regions:
      -
        object: place_object
        target: table
        random_type: A_on_B_region_sampler
        random_config:
          pos_range: [
            [0, -0.20, 0.0],
            [0, -0.15, 0.0]
          ]
          yaw_rotation: [-180, 180]
      -
        object: pick_object_left2
        target: table
        random_type: A_on_B_region_sampler
        random_config:
          pos_range: [
            [-0.30, -0.30, 0.0],
            [-0.15, -0.05, 0.0]
          ]
          yaw_rotation: [-180, 180]
      -
        object: pick_object_right1
        target: table
        random_type: A_on_B_region_sampler
        random_config:
          pos_range: [
            [0.15, -0.3, 0.0],
            [0.3, -0.05, 0.0]
          ]
          yaw_rotation: [-180, 180]
      -
        object: split_aloha
        target: table
        random_type: A_on_B_region_sampler
        random_config:
          pos_range: [
            [-0.025, -0.885, -0.765],
            [0.025, -0.835, -0.765]
          ]
          # ]
          yaw_rotation: [0.0, 0.0]

    cameras:
      -
        name: split_aloha_hand_left
        translation: [0.0, 0.08, 0.05]
        orientation: [0.0, 0.0, 0.965, 0.259]
        camera_axes: usd
        camera_file: workflows/simbox/core/configs/cameras/astra.yaml

        parent: "split_aloha/split_aloha_mid_360_with_piper/split_aloha_mid_360_with_piper/fl/link6"  # todo
        apply_randomization: False
      -
        name: split_aloha_hand_right
        translation: [0.0, 0.08, 0.04]
        orientation: [0.0, 0.0, 0.972, 0.233]
        camera_axes: usd
        camera_file: workflows/simbox/core/configs/cameras/astra.yaml
        parent: "split_aloha/split_aloha_mid_360_with_piper/split_aloha_mid_360_with_piper/fr/link6"  # todo
        apply_randomization: False
      -
        name: split_aloha_head
        translation: [0.0, -0.00818, 0.1]
        orientation: [0.658, 0.259, -0.282, -0.648]
        camera_axes: usd
        camera_file: workflows/simbox/core/configs/cameras/realsense_d455_v3.yaml
        parent: "split_aloha/split_aloha_mid_360_with_piper/split_aloha_mid_360_with_piper/top_camera_link"  # todo: robot base frame

    data:
      task_dir: "stack_bowls"
      language_instruction: "Pick up the bowls and stack them."
      detailed_language_instruction: "Pick up the bowls and stack them."
      collect_info: "three_lr"
      version: "v3.0, head camerea 1280x720, wrist 640x480, y 45 degrees"
      update: True
      max_episode_length: 1000

    skills:
      -
        split_aloha:
          -
            left:
              -
                name: pick
                objects: [pick_object_left2]
                filter_y_dir: ["forward", 90]
                filter_z_dir: ["downward", 160]
                t_eps: 0.01
                o_eps: 1
                pre_grasp_offset: 0
                gripper_change_steps: 10
                post_grasp_offset_min: 0.1
                post_grasp_offset_max: 0.1
              -
                name: place
                objects: [pick_object_left2, place_object]
                filter_z_dir: ["downward", 150]
                x_ratio_range: [0.5, 0.5]
                y_ratio_range: [0.5, 0.5]
                align_pick_obj_axis: [0, 1, 0]
                align_place_obj_axis: [0, 1, 0]
                align_obj_tol: 10
                place_z_offset: 0.14
                position_constraint: object
                success_mode: xybbox
              -
                name: heuristic__skill
                mode: home
                gripper_state: 1.0 # Open gripper
          -
            right:
              -
                name: pick
                objects: [pick_object_right1]
                filter_y_dir: ["forward", 90]
                filter_z_dir: ["downward", 160]
                t_eps: 0.01
                o_eps: 1
                pre_grasp_offset: 0
                gripper_change_steps: 10
                post_grasp_offset_min: 0.1
                post_grasp_offset_max: 0.1
              -
                name: place
                objects: [pick_object_right1, place_object]
                filter_z_dir: ["downward", 150]
                x_ratio_range: [0.5, 0.5]
                y_ratio_range: [0.5, 0.5]
                align_pick_obj_axis: [0, 1, 0]
                align_place_obj_axis: [0, 1, 0]
                align_obj_tol: 10
                place_z_offset: 0.08
                position_constraint: object
                success_mode: xybbox
              -
                name: heuristic__skill
                mode: home
                gripper_state: 1.0 # Open gripper
