tasks:
  -
    name: banana_base_task  # task name
    asset_root: workflows/simbox/assets
    task: BananaBaseTask  # !! where you specify TASK class
    task_id: 0

    offset: null
    render: True

    # Arena configuration
    arena_file: workflows/simbox/core/configs/arenas/pick_clean_arena.yaml

    neglect_collision_names: ["table"]

    env_map:
      envmap_lib: envmap_lib
      apply_randomization: True
      intensity_range: [4000, 7000]
      rotation_range: [0, 180]

    robots:
      -
        name: "genie1"
        robot_config_file: workflows/simbox/core/configs/robots/genie1.yaml
        euler: [0.0, 0.0, 90.0]
        # constrain_grasp_approach: True
        ignore_substring: ["material", "table"]
        use_batch: True

    objects:
      -
        name: pick_object_right
        path: pick_and_place/pre-train-pick/assets/omniobject3d-lemon/xxx/xxx.usd
        target_class: RigidObject
        dataset: oo3d
        category: "omniobject3d-lemon"
        prim_path_child: Aligned
        translation: [0.0, 0.0, 0.0]
        euler: [0.0, 0.0, 0.0]  # stable init pose
        scale: [0.001, 0.001, 0.001] #[1, 1, 1] #
        apply_randomization: True
        orientation_mode: "suggested"
        # optimize_2d_layout: True

    regions:
      -
        object: pick_object_right
        target: table
        random_type: A_on_B_region_sampler
        random_config:
          pos_range: [
            [-0.15, -0.16, 0.0],
            [0.25, 0.0, 0.0]
          ]
          yaw_rotation: [-180.0, 180.0]

      -
        object: ${tasks.0.robots.0.name}
        target: table
        random_type: A_on_B_region_sampler
        random_config:
          pos_range: [
            [0.0, -0.85, -0.85],
            [0.0, -0.80, -0.73]
          ]
          yaw_rotation: [0.0, 0.0]

    distractors:
      path: pick_and_place/pre-train-pick/assets
      min_num: 5
      max_num: 10
      scale: [0.001, 0.001, 0.001]
      target: table
      pos_range: [
        [-0.6, -0.35],
        [0.6, 0.35]
      ]
      min_object_distance: 0.03
      exclude_keywords: ["shoe", "book", "hair_dryer", "box", "cube", "whistle", "discarded", "ball"]

    cameras:
      -
        name: ${tasks.0.robots.0.name}_hand_left
        translation: [-0.01, -0.07, 0.08]
        orientation: [0.191, 0.981, 0.003, 0.017]
        camera_axes: usd
        camera_file: workflows/simbox/core/configs/cameras/realsense_d405_v2.yaml

        parent: "${tasks.0.robots.0.name}/gripper_l_base_link"  # todo
        apply_randomization: False
      -
        name: ${tasks.0.robots.0.name}_hand_right
        translation: [0.015, 0.094, 0.07]
        orientation: [0.0, 0.0, 0.974, 0.225]
        camera_axes: usd
        camera_file: workflows/simbox/core/configs/cameras/realsense_d405_v2.yaml
        parent: "${tasks.0.robots.0.name}/gripper_r_base_link"
        apply_randomization: False
      -
        name: ${tasks.0.robots.0.name}_head
        translation: [0.05, -0.05, -0.0]
        orientation: [0.0, 0.697, 0.0128, -0.717]
        camera_axes: usd
        camera_file: workflows/simbox/core/configs/cameras/realsense_d455_v3.yaml
        parent: "${tasks.0.robots.0.name}/head_link2"

    data:
      task_dir: "single_pick/right/omniobject3d-lemon"
      language_instruction: "Pick up the ${tasks.0.objects.0.name} with the right arm."
      detailed_language_instruction: "Pick up the ${tasks.0.objects.0.name} with the right robotic arm."
      collect_info: ""
      version: "v3.0, head camerea 1280x720, wrist 640x480, y 45 degrees"
      update: True
      max_episode_length: 300

    skills:
      -
        genie1:
          -
            right:
              -
                name: pick
                objects: [pick_object_right]
                # filter_x_dir: ["forward", 130]
                # filter_y_dir: ["backward", 100]
                # filter_z_dir: ["downward", 90]
                filter_x_dir: ["forward", 45]
                filter_y_dir: ["downward", 120]
                filter_z_dir: ["forward", 135]
                pre_grasp_offset: 0.05
                gripper_change_steps: 20
                t_eps: 0.01
                o_eps: 1
                process_valid: True
                lift_th: 0.0
                post_grasp_offset_min: 0.0
                post_grasp_offset_max: 0.0
                # return_to_pregrasp: True
