tasks:
  -
    name: banana_base_task  # task name
    asset_root: workflows/simbox/assets
    task: BananaBaseTask  # !! where you specify TASK class
    task_id: 0

    offset: null
    render: True


    # Arena configuration
    arena_file: workflows/simbox/core/configs/arenas/pick_randomized_arena.yaml
    # arena_file: workflows/simbox/core/configs/arenas/scene_arena.yaml

    env_map:
      envmap_lib: envmap_lib
      apply_randomization: True
      intensity_range: [4000, 7000]
      rotation_range: [0, 180]

    neglect_collision_names: ["table"]

    robots:
      -
        name: "lift2"
        robot_config_file: workflows/simbox/core/configs/robots/lift2.yaml
        euler: [0.0, 0.0, 90.0]
        left_joint_home: [-0.00059017,  0.00374724,  0.00516233,  0.00025332, -0.00105036, -0.00132419]
        right_joint_home: [-0.00059017,  0.00374724,  0.00516233,  0.00025332, -0.00105036, -0.00132419]
        left_joint_home_std: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
        right_joint_home_std: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
        # constrain_grasp_approach: True

    objects:
      -
        name: tooth_brush
        path: basic/store_the_toothbrushes_sim2real/omniobject3d-tooth_brush/toothbrush_0/Aligned_obj.usd
        target_class: RigidObject
        dataset: oo3d
        category: bottle
        prim_path_child: Aligned
        translation: [0.0, 0.0, 0.0]
        euler: [0.0, 0.0, 0.0]  # stable init pose
        scale: [1, 1, 1]
        apply_randomization: False
        optimize_2d_layout: False
      -
        name: tooth_paste
        path: basic/store_the_toothbrushes_sim2real/omniobject3d-tooth_paste/toothpaste_0/Aligned_obj.usd
        target_class: RigidObject
        dataset: oo3d
        category: bottle
        prim_path_child: Aligned
        translation: [0.0, 0.0, 0.0]
        euler: [0.0, 0.0, 0.0]  # stable init pose
        scale: [1, 1, 1]
        apply_randomization: False
        optimize_2d_layout: False
      -
        name: mug
        path: basic/store_the_toothbrushes_sim2real/omniobject3d-mug/mug_0/Aligned_obj.usd
        target_class: RigidObject
        dataset: gso
        category: box
        prim_path_child: Aligned
        translation: [0.0, 0.0, 0.0]
        euler: [90.0, 0.0, 0.0]
        scale: [1, 1, 1]
        apply_randomization: False
        optimize_2d_layout: False

    regions:
      -
        object: tooth_brush
        target: table
        random_type: A_on_B_region_sampler
        random_config:
          pos_range: [
            [-0.45, -0.25, 0.0],
            [-0.2, -0.05, 0.0]
          ]
          yaw_rotation: [-60.0, 60.0]
      -
        object: tooth_paste
        target: table
        random_type: A_on_B_region_sampler
        random_config:
          pos_range: [
            [0.2, -0.25, 0.0],
            [0.45, -0.05, 0.0]
          ]
          yaw_rotation: [-60.0, 60.0]
      -
        object: mug
        target: table
        random_type: A_on_B_region_sampler
        random_config:
          pos_range: [
            [-0.15, -0.25, 0.0],
            [0.15, -0.05, 0.0]
          ]
          yaw_rotation: [0.0, 0.0]
      -
        object: lift2
        target: table
        random_type: A_on_B_region_sampler
        random_config:
          pos_range: [
            [-0.025, -0.8, -0.7],
            [0.025, -0.8, -0.6]
          ]
          yaw_rotation: [0.0, 0.0]

    cameras:
      -
        name: lift2_hand_left
        translation: [0.07, 0.01, 0.08]
        orientation: [0.62, 0.33, -0.33, -0.62]
        camera_axes: usd
        camera_file: workflows/simbox/core/configs/cameras/realsense_d405.yaml
        parent: "lift2/lift2/lift2/fl/link6"  # todo
        apply_randomization: True
        max_translation_noise: 0.02
        max_orientation_noise: 2.5
      -
        name: lift2_hand_right
        translation: [0.07, 0.01, 0.08]
        orientation: [0.62, 0.33, -0.33, -0.62]
        camera_axes: usd
        camera_file: workflows/simbox/core/configs/cameras/realsense_d405.yaml
        parent: "lift2/lift2/lift2/fr/link6"
        apply_randomization: True
        max_translation_noise: 0.02
        max_orientation_noise: 2.5
      -
        name: lift2_head
        translation: [0.1, 0.02, 0.03]
        orientation: [0.6602, 0.2534, -0.2534, -0.6602]
        camera_axes: usd
        camera_file: workflows/simbox/core/configs/cameras/realsense_d455_v3.yaml
        parent: "lift2/lift2/lift2/h_link6"  # todo: robot base frame
        apply_randomization: True
        max_translation_noise: 0.03
        max_orientation_noise: 5.0


    data:
      task_dir: "store_the_toothbrushes_sim2real"
      language_instruction: "Put the toothpaste and toothbrush into the mug."
      detailed_language_instruction: "Pick the toothbrush with left arm and the toothpaste with right arm meanwhile, and then place the toothbrush into the mug, and finally place the toothpaste into the mug."
      collect_info: ""
      version: "v3.0, head camerea 1280x720, wrist 640x480, y 45 degrees"
      update: True
      max_episode_length: 4000

    skills:
      -
        lift2:
          -
            right:
              -
                name: pick
                objects: [tooth_paste]
                filter_z_dir: ["forward", 60]
                filter_x_dir: ["downward", 160]
                pre_grasp_offset: 0.05
                gripper_change_steps: 10
                t_eps: 0.025
                o_eps: 1
                process_valid: True
                lift_th: 0.02
                post_grasp_offset_min: 0.10
                post_grasp_offset_max: 0.15
            left:
              -
                name: pick
                objects: [tooth_brush]
                filter_z_dir: ["forward", 60]
                filter_x_dir: ["downward", 160]
                pre_grasp_offset: 0.05
                gripper_change_steps: 10
                t_eps: 0.025
                o_eps: 1
                process_valid: True
                lift_th: 0.02
                post_grasp_offset_min: 0.10
                post_grasp_offset_max: 0.15
          -
            left:
              -
                name: place
                objects: [tooth_brush, mug]
                place_direction: vertical
                filter_z_dir: ["upward", 40]
                align_pick_obj_axis: [0, 1, 0]
                align_place_obj_axis: [0, 1, 0]
                align_obj_tol: 15 # degree
                pre_place_z_offset: 0.22
                place_z_offset: 0.17
                position_constraint: object
                x_ratio_range: [0.5,0.5]
                y_ratio_range: [0.35,0.5]
                success_th: 0.05
                success_mode: flower
          -
            left:
              -
                name: heuristic__skill
                mode: home
                gripper_state: 1.0 # Open gripper
            right:
              -
                name: place
                objects: [tooth_paste, mug]
                place_direction: vertical
                filter_z_dir: ["upward", 40]
                align_pick_obj_axis: [0, 1, 0]
                align_place_obj_axis: [0, 1, 0]
                align_obj_tol: 15 # degree
                pre_place_z_offset: 0.22
                place_z_offset: 0.17
                position_constraint: object
                x_ratio_range: [0.5,0.5]
                y_ratio_range: [0.35,0.5]
                success_th: 0.05
                success_mode: flower
              -
                name: heuristic__skill
                mode: home
                gripper_state: 1.0 # Open gripper
