tasks:
  -
    name: banana_base_task  # task name
    asset_root: workflows/simbox/assets
    task: BananaBaseTask  # !! where you specify TASK class
    task_id: 0

    offset: null
    render: True


    # Arena configuration
    arena_file: workflows/simbox/core/configs/arenas/pick_randomized_arena.yaml
    # arena_file: workflows/simbox/core/configs/arenas/scene_arena.yaml

    env_map:
      envmap_lib: envmap_lib
      apply_randomization: True
      intensity_range: [4000, 7000]
      rotation_range: [0, 180]

    neglect_collision_names: ["table"]

    robots:
      -
        name: "lift2"
        robot_config_file: workflows/simbox/core/configs/robots/lift2.yaml
        euler: [0.0, 0.0, 90.0]
        left_joint_home: [-0.00059017,  0.00374724,  0.00516233,  0.00025332, -0.00105036, -0.00132419]
        right_joint_home: [-0.00059017,  0.00374724,  0.00516233,  0.00025332, -0.00105036, -0.00132419]
        left_joint_home_std: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
        right_joint_home_std: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
        tcp_offset: 0.115
    objects:
      -
        name: arcode_plate_blue
        path: basic/sort_the_tray_on_rack/plate/plate_blue/Aligned_obj.usd
        target_class: RigidObject
        dataset: arcode
        category: plate
        prim_path_child: Aligned
        translation: [0.0, 0.0, 0.0]
        euler: [90.0, 0.0, 0.0]
        scale: [1.0, 1.0, 1.0]
      -
        name: arcode_plate_shelf
        path: basic/sort_the_tray_on_rack/plate_shelf/shelf_0/Aligned_obj.usd
        target_class: RigidObject
        dataset: arcode
        category: plate
        prim_path_child: Aligned
        translation: [0.0, 0.0, 0.0]
        euler: [90.0, 0.0, 0.0]
        scale: [1.0, 1.0, 1.0]

    regions:
      -
        object: ${tasks.0.robots.0.name}
        target: table
        random_type: A_on_B_region_sampler
        random_config:
          pos_range: [
            [-0.025, -0.75, -0.72],
            [0.025, -0.75, -0.72]
          ]
          yaw_rotation: [-0.0, 0.0]
      -
        object: arcode_plate_blue
        target: table
        random_type: A_on_B_region_sampler
        random_config:
          pos_range: [
            [0.125, -0.20, 0.005],
            [0.25, -0.10, 0.005]
          ]
          yaw_rotation: [0, 0]
      -
        object: arcode_plate_shelf
        target: table
        random_type: A_on_B_region_sampler
        random_config:
          pos_range: [
            [-0.25, -0.20, 0.005],
            [-0.15, -0.10, 0.005]
          ]
          yaw_rotation: [0, 0]

    cameras:
      -
        name: lift2_hand_left
        translation: [0.07, 0.01, 0.08]
        orientation: [0.62, 0.33, -0.33, -0.62]
        camera_axes: usd
        camera_file: workflows/simbox/core/configs/cameras/realsense_d405.yaml
        parent: "lift2/lift2/lift2/fl/link6"  # todo
        apply_randomization: True
        max_translation_noise: 0.02
        max_orientation_noise: 2.5
      -
        name: lift2_hand_right
        translation: [0.07, 0.01, 0.08]
        orientation: [0.62, 0.33, -0.33, -0.62]
        camera_axes: usd
        camera_file: workflows/simbox/core/configs/cameras/realsense_d405.yaml
        parent: "lift2/lift2/lift2/fr/link6"
        apply_randomization: True
        max_translation_noise: 0.02
        max_orientation_noise: 2.5
      -
        name: lift2_head
        translation: [0.1, 0.02, 0.03]
        orientation: [0.6602, 0.2534, -0.2534, -0.6602]
        camera_axes: usd
        camera_file: workflows/simbox/core/configs/cameras/realsense_d455_v3.yaml
        parent: "lift2/lift2/lift2/h_link6"  # todo: robot base frame
        apply_randomization: True
        max_translation_noise: 0.03
        max_orientation_noise: 5.0


    data:
      task_dir: "sort_the_tray_on_rack"
      language_instruction: "Pick the plate, make the handover and place it on the water cooling holder."
      detailed_language_instruction: "Pick the plate with the right arm, make the handover to the left arm, and then place it on the water cooling holder."
      collect_info: ""
      version: "v3.0, head camerea 1280x720, wrist 640x480, y 45 degrees"
      update: True
      max_episode_length: 1300

    skills:
      -
        lift2:
          -
            right:
              -
                name: pick
                objects: [arcode_plate_blue]
                filter_y_dir: ["upward", 90, 45]
                filter_z_dir: ["forward", 40]
                filter_x_dir: ["downward", 110, 140]
                t_eps: 0.01
                o_eps: 1
                gripper_change_steps: 10
                post_grasp_offset_min: 0.1
                post_grasp_offset_max: 0.1
                direction_to_obj: right
              -
                name: goto__pose
                frame: robot
                gripper_state: -1 # Close
                # translation: [0.28, 0.13, 0.30]
                position: [0.3, 0.03, 0.1]
                # quaternion: [0.22, 0.44, 0.78, 0.37] # -147, 43, -134,
                quaternion: [0.92, 0.02, 0.06, 0.38]
                interp_nums: 1
          -
            left:
              -
                name: pick
                objects: [arcode_plate_blue]
                filter_z_dir: ["upward", 40]
                filter_x_dir: ["forward", 90, 45]
                gripper_change_steps: 10
                t_eps: 0.01
                o_eps: 1
                post_grasp_offset_min: 0.0
                post_grasp_offset_max: 0.0
                direction_to_obj: left
          -
            left:
              -
                name: gripper__action
                gripper_state: -1 # Close
            right:
              -
                name: gripper__action
                gripper_state: 1 # Open
          -
            right:
              -
                name: heuristic__skill
                mode: home
                gripper_state: 1.0 # Open gripper
          -
            left:
              -
                name: place
                place_direction: vertical
                objects: [arcode_plate_blue, arcode_plate_shelf]
                filter_z_dir: ["upward", 60, 0]
                filter_x_dir: ["forward", 90, 30]
                position_constraint: object
                x_ratio_range: [0.5, 0.5]
                y_ratio_range: [0.8, 0.8]
                align_pick_obj_axis: [0, 1, 0]
                align_place_obj_axis: [0, 0, 1]
                align_obj_tol: 10
                pre_place_z_offset: 0.15
                place_z_offset: 0.01
